version: "3.5"
services:
  nexus:
    image: earlpomeroy/sonatype-nexus3:3.23.0
    volumes:
      - ~/tmp/nexus-data:/nexus-data
    environment:
      APPLICATION_PASSWORD: /run/secrets/apppass
    secrets:
      - apppass
    ports:
      - 8081:8081

secrets:
  apppass:
    external: true
